services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    ports:
      - "8001:8000"

  backend:
    build: .
    depends_on:
      - dynamodb-local
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    env_file:
      - path: .env
        required: true
    volumes:
      - .:/app
    command:
      [
        "uvicorn",
        "main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]
    restart: unless-stopped
